### ISSUE TITLE
Is this the latest version?

### ISSUE THREAD

**Issue by wiwile** [domw95/tiles-web#7]
The project is great! Is this the latest version? I feel that the version I downloaded and ran is not as intelligent as your online demo version. Is it just my imagination?

**Comment by domw95** [comment]
It's been a while since I've looked at this but I think maybe the latest changes I made haven't been released yet and are stuck on the dev branch https://github.com/domw95/tiles-web/tree/new-personalities

**Comment by wiwile** [comment]
OK! Got it. Thank you!
